# Generated by Django 6.0.7 on 2026-07-18 10:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("plaid_integration", "0001_initial"),
        ("records", "0019_folder_record_folder"),
    ]

    operations = [
        migrations.AddField(
            model_name="transaction",
            name="record",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="plaid_transaction",
                to="records.record",
            ),
        ),
    ]
