# Generated by Django 6.0.7 on 2026-07-18 21:12

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("plaid_integration", "0002_transaction_record"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Transaction",
        ),
    ]
