# Generated by Django 6.0.7 on 2026-07-19 05:13

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("plaid_integration", "0003_delete_transaction"),
    ]

    operations = [
        migrations.AddField(
            model_name="plaiditem",
            name="last_error_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="plaiditem",
            name="last_error_code",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="plaiditem",
            name="last_error_message",
            field=models.TextField(blank=True, null=True),
        ),
    ]
