# Generated by Django 6.0.7 on 2026-07-19 05:28

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "plaid_integration",
            "0004_plaiditem_last_error_at_plaiditem_last_error_code_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="plaiditem",
            name="account_name",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
