# Generated by Django 6.0.7 on 2026-07-19 05:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("plaid_integration", "0005_plaiditem_account_name"),
    ]

    operations = [
        migrations.RenameField(
            model_name="plaiditem",
            old_name="account_name",
            new_name="institution_name",
        ),
        migrations.AddField(
            model_name="plaiditem",
            name="accounts_data",
            field=models.JSONField(blank=True, null=True),
        ),
    ]
