# Generated by Django 6.0.6 on 2026-07-12 05:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usersettings',
            old_name='auto_archive_expired',
            new_name='auto_archive_expired_records',
        ),
        migrations.RenameField(
            model_name='usersettings',
            old_name='auto_delete_archived',
            new_name='auto_delete_archived_records',
        ),
    ]
