# Generated by Django 6.0.7 on 2026-07-16 23:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0004_usersettings_expiring_notifications_advance_time_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="usersettings",
            name="enable_email_notifications",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="usersettings",
            name="enable_push_notifications",
            field=models.BooleanField(default=True),
        ),
    ]
