# Generated by Django 6.0.7 on 2026-07-19 02:52

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0005_usersettings_enable_email_notifications_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="usersettings",
            name="auto_create_and_organize_folders",
            field=models.BooleanField(default=True),
        ),
    ]
