# Generated by Django 6.0.7 on 2026-07-21 06:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0006_usersettings_auto_create_and_organize_folders"),
    ]

    operations = [
        migrations.AddField(
            model_name="usersettings",
            name="auto_delete_deleted_documents",
            field=models.BooleanField(default=True),
        ),
    ]
