from .base import (
    INSTALLED_APPS,
    MIDDLEWARE,
    STORAGES,
)

CSRF_TRUSTED_ORIGINS = []
CORS_ALLOW_ALL_ORIGINS = False

SECURE_SSL_REDIRECT = True
SESSION_COOKIE_SECURE = True
CSRF_COOKIE_SECURE = True

ALLOWED_HOSTS = []
