from django.core.mail import EmailMultiAlternatives, get_connection
from django_qstash import stashed_task


@stashed_task
def send_background_email(
    subject, message, from_email, recipient_list, html_message=None
):
    # 1. FORCE Anymail's Resend backend directly for this execution step
    # This specifically avoids using the project's global EMAIL_BACKEND setting
    resend_connection = get_connection(backend="anymail.backends.resend.EmailBackend")

    # 2. Build the email framework
    email = EmailMultiAlternatives(
        subject=subject,
        body=message,
        from_email=from_email,
        to=recipient_list,
        connection=resend_connection,  # Bind strictly to the Resend API channel
    )

    # 3. Attach HTML alternate version if generated by django-allauth
    if html_message:
        email.attach_alternative(html_message, "text/html")

    # 4. Dispatch the message directly to Resend's API
    email.send()
