# Generated by Django 6.0.6 on 2026-06-30 00:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0004_alter_document_data_associated_record'),
        ('records', '0003_alter_record_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document_data',
            name='associated_record',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='records.record'),
        ),
    ]
