# Generated by Django 6.0.6 on 2026-06-30 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0005_alter_document_data_associated_record'),
    ]

    operations = [
        migrations.AddField(
            model_name='document_data',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('processed', 'Processed'), ('attached', 'Attached'), ('error', 'Error')], default='pending', max_length=50),
        ),
    ]
