# Generated by Django 6.0.6 on 2026-06-30 18:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0006_document_data_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='document_data',
            name='status',
        ),
    ]
