# Generated by Django 6.0.6 on 2026-07-04 07:08

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("documents", "0008_document_data_is_main"),
    ]

    operations = [
        migrations.AddField(
            model_name="document_data",
            name="notes",
            field=models.TextField(blank=True, null=True),
        ),
    ]
