# Generated by Django 6.0.6 on 2026-07-04 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("documents", "0009_document_data_notes"),
    ]

    operations = [
        migrations.AddField(
            model_name="document_data",
            name="title",
            field=models.CharField(default="Untitled", max_length=200),
        ),
    ]
