# Generated by Django 6.0.6 on 2026-07-12 08:57

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("documents", "0011_rename_document_data_documentdata"),
    ]

    operations = [
        migrations.AddField(
            model_name="documentdata",
            name="file_extension",
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
