# Generated by Django 6.0.6 on 2026-07-14 00:43

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("documents", "0013_documentdata_documents_d_user_id_a6b392_idx_and_more"),
        ("records", "0014_record_records_rec_user_id_4d2ecf_idx_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name="documentdata",
            name="documents_d_date_ad_26a650_idx",
        ),
        migrations.AddField(
            model_name="documentdata",
            name="file_hash",
            field=models.CharField(default="", max_length=64, unique=True),
            preserve_default=False,
        ),
        migrations.AddIndex(
            model_name="documentdata",
            index=models.Index(
                fields=["date_added", "file_hash"],
                name="documents_d_date_ad_aee3a6_idx",
            ),
        ),
    ]
