# Generated by Django 6.0.6 on 2026-07-14 02:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("documents", "0015_alter_documentdata_file_hash_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="documentdata",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", "Pending"),
                    ("processed", "Processed"),
                    ("error", "Error"),
                ],
                default="pending",
                max_length=10,
            ),
        ),
    ]
