# Generated by Django 6.0.6 on 2026-07-14 02:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("documents", "0016_documentdata_status"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="documentdata",
            name="status",
        ),
    ]
