# Generated by Django 6.0.6 on 2026-07-14 08:36

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("documents", "0018_documentdata_status_with_choices"),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name="documentdata",
            name="documents_doc_status_date_idx",
        ),
        migrations.RenameIndex(
            model_name="documentdata",
            new_name="idx_doc_user_status",
            old_name="documents_doc_user_status_idx",
        ),
        migrations.AlterField(
            model_name="documentdata",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending_upload", "Pending Upload"),
                    ("uploading", "Uploading"),
                    ("uploaded", "Uploaded"),
                    ("validating", "Validating"),
                    ("processing", "Processing OCR"),
                    ("completed", "Completed"),
                    ("error", "Error"),
                    ("deleting", "Deleting"),
                ],
                default="pending_upload",
                max_length=20,
            ),
        ),
    ]
