# Generated by Django 6.0.6 on 2026-07-14 08:45

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "documents",
            "0019_remove_documentdata_documents_doc_status_date_idx_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="documentdata",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending_upload", "Pending Upload"),
                    ("uploaded", "Uploaded"),
                    ("processing", "Processing OCR"),
                    ("completed", "Completed"),
                    ("error", "Error"),
                    ("deleting", "Deleting"),
                ],
                default="pending_upload",
                max_length=20,
            ),
        ),
    ]
