# Generated by Django 6.0.6 on 2026-07-15 21:46

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("documents", "0021_documentdata_idx_doc_list_cover_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="documentdata",
            options={"ordering": ["-date_added"]},
        ),
        migrations.RenameIndex(
            model_name="documentdata",
            new_name="idx_doc_user_record",
            old_name="documents_d_user_id_a6b392_idx",
        ),
        migrations.RenameIndex(
            model_name="documentdata",
            new_name="idx_doc_user_ext",
            old_name="documents_d_user_id_1a7656_idx",
        ),
        migrations.RenameIndex(
            model_name="documentdata",
            new_name="idx_doc_date_hash",
            old_name="documents_d_date_ad_aee3a6_idx",
        ),
        migrations.AddField(
            model_name="documentdata",
            name="created_at",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name="documentdata",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name="documentdata",
            name="date_added",
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name="documentdata",
            name="file_extension",
            field=models.CharField(blank=True, default="", max_length=10),
        ),
        migrations.AlterField(
            model_name="documentdata",
            name="file_hash",
            field=models.CharField(db_index=True, max_length=64),
        ),
        migrations.AlterField(
            model_name="documentdata",
            name="id",
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name="documentdata",
            name="notes",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AlterField(
            model_name="documentdata",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending_upload", "Pending Upload"),
                    ("uploaded", "Uploaded"),
                    ("processing", "Processing OCR"),
                    ("completed", "Completed"),
                    ("error", "Error"),
                    ("deleting", "Deleting"),
                ],
                db_index=True,
                default="pending_upload",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="documentdata",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="documents",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
