# Generated by Django 6.0.7 on 2026-07-17 00:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("documents", "0023_documentdata_idx_doc_orphaned_cleanup_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="documentdata",
            name="ocr_retries",
            field=models.PositiveSmallIntegerField(default=0),
        ),
    ]
