# Generated by Django 6.0.7 on 2026-07-17 00:33

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("documents", "0024_documentdata_ocr_retries"),
    ]

    operations = [
        migrations.AddField(
            model_name="documentdata",
            name="ocr_error",
            field=models.TextField(blank=True, default=""),
        ),
    ]
