# Generated by Django 6.0.7 on 2026-07-21 07:00

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("documents", "0026_documentdata_deleted_at"),
    ]

    operations = [
        migrations.AddField(
            model_name="documentdata",
            name="file_size",
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="documentdata",
            name="mime_type",
            field=models.CharField(blank=True, default="", max_length=100),
        ),
        migrations.AddField(
            model_name="documentdata",
            name="ocr_metadata",
            field=models.JSONField(blank=True, null=True),
        ),
    ]
