# Generated by Django 6.0.7 on 2026-07-21 07:47

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("documents", "0027_documentdata_file_size_documentdata_mime_type_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="documentdata",
            name="is_active",
            field=models.BooleanField(db_index=True, default=True),
        ),
    ]
