# Generated by Django 6.0.7 on 2026-07-21 08:39

import django.db.models.deletion
import django.utils.timezone
import simple_history.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("documents", "0029_backfill_is_active"),
        ("records", "0028_historicalrecord"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="HistoricalDocumentData",
            fields=[
                ("id", models.BigIntegerField(blank=True, db_index=True)),
                ("title", models.CharField(default="Untitled", max_length=200)),
                ("filepath", models.CharField(max_length=500)),
                (
                    "date_added",
                    models.DateTimeField(blank=True, db_index=True, editable=False),
                ),
                ("did_ocr", models.BooleanField(default=False)),
                ("ocr_retries", models.PositiveSmallIntegerField(default=0)),
                ("ocr_error", models.TextField(blank=True, default="")),
                ("ocr_metadata", models.JSONField(blank=True, null=True)),
                ("notes", models.TextField(blank=True, default="")),
                (
                    "file_extension",
                    models.CharField(blank=True, default="", max_length=10),
                ),
                ("file_size", models.BigIntegerField(blank=True, null=True)),
                ("mime_type", models.CharField(blank=True, default="", max_length=100)),
                ("file_hash", models.CharField(db_index=True, max_length=64)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending_upload", "Pending Upload"),
                            ("uploaded", "Uploaded"),
                            ("processing", "Processing OCR"),
                            ("completed", "Completed"),
                            ("error", "Error"),
                            ("deleting", "Deleting"),
                        ],
                        db_index=True,
                        default="pending_upload",
                        max_length=20,
                    ),
                ),
                ("is_active", models.BooleanField(db_index=True, default=True)),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("updated_at", models.DateTimeField(blank=True, editable=False)),
                (
                    "deleted_at",
                    models.DateTimeField(blank=True, db_index=True, null=True),
                ),
                ("history_id", models.AutoField(primary_key=True, serialize=False)),
                ("history_date", models.DateTimeField(db_index=True)),
                ("history_change_reason", models.CharField(max_length=100, null=True)),
                (
                    "history_type",
                    models.CharField(
                        choices=[("+", "Created"), ("~", "Changed"), ("-", "Deleted")],
                        max_length=1,
                    ),
                ),
                (
                    "associated_record",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="records.record",
                    ),
                ),
                (
                    "history_user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "historical document data",
                "verbose_name_plural": "historical document datas",
                "ordering": ("-history_date", "-history_id"),
                "get_latest_by": ("history_date", "history_id"),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
    ]
