# Generated by Django 6.0.7 on 2026-07-23 11:01

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("documents", "0030_historicaldocumentdata"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="documentdata",
            name="created_at",
        ),
        migrations.RemoveField(
            model_name="historicaldocumentdata",
            name="created_at",
        ),
    ]
