# Generated by Django 6.0.6 on 2026-06-28 22:32

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("records", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="record",
            old_name="product",
            new_name="products",
        ),
        migrations.AddField(
            model_name="record",
            name="description",
            field=models.TextField(blank=True, null=True),
        ),
    ]
