# Generated by Django 6.0.6 on 2026-06-30 10:31

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("records", "0006_alter_record_record_type"),
    ]

    operations = [
        migrations.RenameField(
            model_name="record",
            old_name="description",
            new_name="notes",
        ),
    ]
