# Generated by Django 6.0.6 on 2026-07-01 09:52

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("records", "0008_record_last_edited"),
    ]

    operations = [
        migrations.AlterField(
            model_name="record",
            name="last_edited",
            field=models.DateTimeField(auto_now=True),
        ),
    ]
