# Generated by Django 6.0.6 on 2026-07-01 18:42

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("records", "0009_alter_record_last_edited"),
    ]

    operations = [
        migrations.AddField(
            model_name="record",
            name="color_group",
            field=models.CharField(
                blank=True,
                choices=[
                    ("slate", "Slate / Gray"),
                    ("red", "Red"),
                    ("orange", "Orange"),
                    ("amber", "Amber"),
                    ("yellow", "Yellow"),
                    ("lime", "Lime"),
                    ("green", "Green"),
                    ("emerald", "Emerald"),
                    ("teal", "Teal"),
                    ("cyan", "Cyan"),
                    ("sky", "Sky"),
                    ("blue", "Blue"),
                    ("indigo", "Indigo"),
                    ("violet", "Violet"),
                    ("purple", "Purple"),
                    ("fuchsia", "Fuchsia"),
                    ("pink", "Pink"),
                    ("rose", "Rose"),
                ],
                max_length=30,
                null=True,
            ),
        ),
    ]
