# Generated by Django 6.0.6 on 2026-07-02 05:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("records", "0010_record_color_group"),
    ]

    operations = [
        migrations.AlterField(
            model_name="record",
            name="color_group",
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
