# Generated by Django 6.0.6 on 2026-07-02 05:06

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("records", "0011_alter_record_color_group"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="record",
            name="color_group",
        ),
    ]
