# Generated by Django 6.0.6 on 2026-07-02 05:42

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("records", "0012_remove_record_color_group"),
    ]

    operations = [
        migrations.AlterField(
            model_name="record",
            name="record_type",
            field=models.CharField(
                choices=[
                    ("expense_receipt", "Expense Receipt"),
                    ("voucher", "Voucher"),
                    ("warranty_certificate", "Warranty Certificate"),
                    ("vendor_invoice", "Vendor Invoice"),
                    ("customer_invoice", "Customer Invoice"),
                    ("loan_document", "Loan Document"),
                    ("credit_card_statement", "Credit Card Statement"),
                    ("bank_statement", "Bank Statement"),
                    ("purchase_order", "Purchase Order"),
                    ("payslip", "Payslip"),
                    ("tax_document", "Tax Document"),
                    ("service_contract", "Service Contract"),
                    ("lease_agreement", "Lease Agreement"),
                    ("insurance_policy", "Insurance Policy"),
                    ("other", "Other"),
                ],
                default="expense_receipt",
                max_length=30,
            ),
        ),
    ]
