# Generated by Django 6.0.6 on 2026-07-14 09:10

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("records", "0014_record_records_rec_user_id_4d2ecf_idx_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name="record",
            index=models.Index(
                fields=["user", "is_active", "-last_edited"],
                name="idx_record_list_cover",
            ),
        ),
        migrations.AddIndex(
            model_name="record",
            index=models.Index(
                fields=["user", "is_active", "record_type"],
                name="idx_record_type_filter",
            ),
        ),
    ]
