# Generated by Django 6.0.7 on 2026-07-16 03:17

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("records", "0016_alter_record_options_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name="record",
            index=models.Index(
                fields=["expiry_date", "is_active", "user"],
                name="idx_record_expiry_active_user",
            ),
        ),
        migrations.AddIndex(
            model_name="record",
            index=models.Index(
                fields=["expiry_date", "is_active", "user", "date_added"],
                name="idx_record_archive_filter",
            ),
        ),
    ]
