# Generated by Django 6.0.7 on 2026-07-16 04:01

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("records", "0017_record_idx_record_expiry_active_user_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="record",
            name="expiry_notification_sent",
            field=models.BooleanField(db_index=True, default=False),
        ),
    ]
