# Generated by Django 6.0.7 on 2026-07-18 21:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("plaid_integration", "0003_delete_transaction"),
        ("records", "0019_folder_record_folder"),
    ]

    operations = [
        migrations.AddField(
            model_name="record",
            name="plaid_item",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="records",
                to="plaid_integration.plaiditem",
            ),
        ),
        migrations.AddField(
            model_name="record",
            name="plaid_transaction_id",
            field=models.CharField(blank=True, max_length=255, null=True, unique=True),
        ),
    ]
