# Generated by Django 6.0.7 on 2026-07-19 02:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("records", "0020_record_plaid_item_record_plaid_transaction_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="record",
            name="folder",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="records",
                to="records.folder",
            ),
        ),
        migrations.AlterField(
            model_name="record",
            name="record_type",
            field=models.CharField(
                choices=[
                    ("expense_receipt", "Expense Receipt"),
                    ("voucher", "Voucher"),
                    ("financial_document", "Financial Document"),
                    ("warranty_certificate", "Warranty Certificate"),
                    ("vendor_invoice", "Vendor Invoice"),
                    ("customer_invoice", "Customer Invoice"),
                    ("loan_document", "Loan Document"),
                    ("credit_card_statement", "Credit Card Statement"),
                    ("bank_statement", "Bank Statement"),
                    ("purchase_order", "Purchase Order"),
                    ("payslip", "Payslip"),
                    ("tax_document", "Tax Document"),
                    ("service_contract", "Service Contract"),
                    ("lease_agreement", "Lease Agreement"),
                    ("insurance_policy", "Insurance Policy"),
                    ("other", "Other"),
                ],
                db_index=True,
                default="expense_receipt",
                max_length=30,
            ),
        ),
    ]
