# Generated by Django 6.0.7 on 2026-07-20 05:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("documents", "0025_documentdata_ocr_error"),
        ("records", "0021_alter_record_folder_alter_record_record_type"),
    ]

    operations = [
        migrations.CreateModel(
            name="MergeLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("plaid_snapshot", models.JSONField()),
                ("document_snapshot", models.JSONField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("undone_at", models.DateTimeField(blank=True, null=True)),
                (
                    "document",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="documents.documentdata",
                    ),
                ),
                (
                    "document_record",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="merge_logs_as_document",
                        to="records.record",
                    ),
                ),
                (
                    "plaid_record",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="merge_logs_as_plaid",
                        to="records.record",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
    ]
