# Generated by Django 6.0.7 on 2026-07-20 07:57

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("documents", "0025_documentdata_ocr_error"),
        ("records", "0022_merge_log"),
    ]

    operations = [
        migrations.AlterField(
            model_name="mergelog",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name="mergelog",
            name="undone_at",
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
        migrations.AddConstraint(
            model_name="mergelog",
            constraint=models.UniqueConstraint(
                condition=models.Q(("undone_at__isnull", True)),
                fields=("plaid_record", "document_record"),
                name="unique_active_merge",
                violation_error_message="An active merge already exists for this pair.",
            ),
        ),
    ]
