# Generated by Django 6.0.7 on 2026-07-20 08:26

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("documents", "0025_documentdata_ocr_error"),
        ("records", "0023_add_merge_log_indexes_and_constraint"),
    ]

    operations = [
        migrations.AddField(
            model_name="mergelog",
            name="search_text",
            field=models.TextField(blank=True),
        ),
        migrations.AddIndex(
            model_name="mergelog",
            index=models.Index(fields=["search_text"], name="idx_mergelog_search"),
        ),
    ]
