# Generated by Django 6.0.7 on 2026-07-21 04:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("records", "0026_record_original_data"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ActivityLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "event",
                    models.CharField(
                        choices=[
                            ("record_created", "Record created"),
                            ("receipt_uploaded", "Receipt uploaded"),
                            ("ocr_completed", "OCR completed"),
                            ("imported_from_plaid", "Imported from Plaid"),
                            ("receipt_matched", "Receipt matched"),
                            ("records_merged", "Records merged"),
                            ("records_unmerged", "Records unmerged"),
                            ("folder_changed", "Folder changed"),
                            ("merchant_edited", "Merchant edited"),
                            ("amount_edited", "Amount edited"),
                            ("title_edited", "Title edited"),
                            ("record_type_changed", "Record type changed"),
                            ("reminder_sent", "Reminder sent"),
                            ("csv_exported", "CSV exported"),
                            ("document_added", "Supporting document added"),
                            ("document_removed", "Supporting document removed"),
                            ("record_archived", "Record archived"),
                            ("record_unarchived", "Record unarchived"),
                            ("record_deleted", "Record deleted"),
                        ],
                        max_length=30,
                    ),
                ),
                ("timestamp", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("metadata", models.JSONField(blank=True, null=True)),
            ],
            options={
                "ordering": ["-timestamp"],
            },
        ),
        migrations.AddField(
            model_name="record",
            name="source_type",
            field=models.CharField(
                choices=[
                    ("ocr", "Receipt OCR"),
                    ("plaid", "Plaid Transaction"),
                    ("manual", "Manual Entry"),
                    ("merged", "Merged Record"),
                ],
                db_index=True,
                default="manual",
                max_length=10,
            ),
        ),
        migrations.AddField(
            model_name="activitylog",
            name="record",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="activity_logs",
                to="records.record",
            ),
        ),
        migrations.AddField(
            model_name="activitylog",
            name="user",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddIndex(
            model_name="activitylog",
            index=models.Index(
                fields=["record", "-timestamp"], name="records_act_record__691744_idx"
            ),
        ),
    ]
