# Generated by Django 6.0.7 on 2026-07-21 23:05

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("records", "0028_historicalrecord"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="historicalrecord",
            name="payment_method_locked",
        ),
        migrations.RemoveField(
            model_name="record",
            name="payment_method_locked",
        ),
        migrations.AddField(
            model_name="historicalrecord",
            name="nickname",
            field=models.CharField(blank=True, default="", max_length=255),
        ),
        migrations.AddField(
            model_name="record",
            name="nickname",
            field=models.CharField(blank=True, default="", max_length=255),
        ),
    ]
