# Generated by Django 6.0.7 on 2026-07-22 20:54

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("records", "0030_add_auditlog_idempotency_key"),
    ]

    operations = [
        migrations.AlterField(
            model_name="historicalrecord",
            name="balance",
            field=models.DecimalField(
                blank=True,
                db_index=True,
                decimal_places=2,
                default=None,
                max_digits=12,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="historicalrecord",
            name="transaction_date",
            field=models.DateField(blank=True, db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name="record",
            name="balance",
            field=models.DecimalField(
                blank=True,
                db_index=True,
                decimal_places=2,
                default=None,
                max_digits=12,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="record",
            name="transaction_date",
            field=models.DateField(blank=True, db_index=True, null=True),
        ),
    ]
